-- Doc365 Hermes Portal — initial schema (PRD §15).
-- Generated by hand to keep the first migration readable; subsequent migrations
-- should use `pnpm db:generate` (drizzle-kit) from the Drizzle schema.

-- Enums ───────────────────────────────────────────────────────────────
CREATE TYPE "user_role" AS ENUM ('user', 'operator');
CREATE TYPE "sender_type" AS ENUM ('user', 'assistant', 'system');
CREATE TYPE "conversation_status" AS ENUM ('active', 'archived');
CREATE TYPE "approval_status" AS ENUM ('not_required', 'pending', 'approved', 'denied', 'expired');
CREATE TYPE "execution_status" AS ENUM ('not_started', 'running', 'succeeded', 'failed');
CREATE TYPE "action_type" AS ENUM (
    'chat',
    'analyze_files',
    'check_pending',
    'validate_submission',
    'draft_recurso',
    'prepare_orizon',
    'submit_orizon'
);

-- Organizations ──────────────────────────────────────────────────────
CREATE TABLE "organizations" (
    "id"         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    "name"       text        NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now()
);

-- Users ──────────────────────────────────────────────────────────────
CREATE TABLE "users" (
    "id"              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    "organization_id" uuid        NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
    "name"            text        NOT NULL,
    "email"           citext      NOT NULL,
    "password_hash"   text        NOT NULL,
    "role"            user_role   NOT NULL DEFAULT 'user',
    "created_at"      timestamptz NOT NULL DEFAULT now(),
    "last_login_at"   timestamptz
);
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");

-- Conversations ──────────────────────────────────────────────────────
CREATE TABLE "conversations" (
    "id"              uuid                PRIMARY KEY DEFAULT gen_random_uuid(),
    "organization_id" uuid                NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
    "user_id"         uuid                NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "title"           text,
    "status"          conversation_status NOT NULL DEFAULT 'active',
    "created_at"      timestamptz         NOT NULL DEFAULT now(),
    "updated_at"      timestamptz         NOT NULL DEFAULT now()
);
CREATE INDEX "conversations_by_user" ON "conversations" ("organization_id", "user_id", "updated_at" DESC);

-- Messages ───────────────────────────────────────────────────────────
CREATE TABLE "messages" (
    "id"              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    "conversation_id" uuid        NOT NULL REFERENCES "conversations"("id") ON DELETE CASCADE,
    "sender_type"     sender_type NOT NULL,
    "content"         text        NOT NULL,
    "created_at"      timestamptz NOT NULL DEFAULT now(),
    "metadata_json"   jsonb
);
CREATE INDEX "messages_by_conversation" ON "messages" ("conversation_id", "created_at");

-- File attachments ───────────────────────────────────────────────────
CREATE TABLE "file_attachments" (
    "id"                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    "conversation_id"       uuid        NOT NULL REFERENCES "conversations"("id") ON DELETE CASCADE,
    "uploaded_by_user_id"   uuid        NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
    "original_name"         text        NOT NULL,
    "mime_type"             text        NOT NULL,
    "size_bytes"            bigint      NOT NULL,
    "storage_key"           text        NOT NULL,
    "checksum"              text,
    "created_at"            timestamptz NOT NULL DEFAULT now(),
    "metadata_json"         jsonb,
    "upload_complete"       boolean     NOT NULL DEFAULT false
);
CREATE INDEX "file_attachments_by_conversation" ON "file_attachments" ("conversation_id");

-- Action requests ────────────────────────────────────────────────────
CREATE TABLE "action_requests" (
    "id"                    uuid              PRIMARY KEY DEFAULT gen_random_uuid(),
    "conversation_id"       uuid              NOT NULL REFERENCES "conversations"("id") ON DELETE CASCADE,
    "requested_by_user_id"  uuid              NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
    "action_type"           action_type       NOT NULL,
    "payload_json"          jsonb,
    "approval_status"       approval_status   NOT NULL DEFAULT 'not_required',
    "execution_status"      execution_status  NOT NULL DEFAULT 'not_started',
    "approved_by_user_id"   uuid              REFERENCES "users"("id"),
    "idempotency_key"       text              NOT NULL,
    "requested_at"          timestamptz       NOT NULL DEFAULT now(),
    "approved_at"           timestamptz,
    "executed_at"           timestamptz,
    "result_summary"        text
);
CREATE INDEX "action_requests_by_conversation" ON "action_requests" ("conversation_id", "approval_status");
CREATE UNIQUE INDEX "action_requests_idempotency_unique" ON "action_requests" ("idempotency_key");

-- Audit events ───────────────────────────────────────────────────────
CREATE TABLE "audit_events" (
    "id"              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    "organization_id" uuid        NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
    "user_id"         uuid        REFERENCES "users"("id"),
    "conversation_id" uuid        REFERENCES "conversations"("id"),
    "action_type"     text        NOT NULL,
    "target_type"     text        NOT NULL,
    "target_id"       text,
    "metadata_json"   jsonb,
    "created_at"      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "audit_events_by_org_time" ON "audit_events" ("organization_id", "created_at" DESC);
